version: '3'

services:

  db:
    image: postgres:15-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=aston_crud_db
      - DATABASE_URL=jdbc:postgresql://db:5432/aston_crud_db